"""add email verified column

Revision ID: cdd2d8732cc8
Revises: 36739ed042a2
Create Date: 2026-06-18 13:17:37.006683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdd2d8732cc8'
down_revision: Union[str, Sequence[str], None] = '36739ed042a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
